<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Bender-ой" name="com.qtpselenium.suiteC.TestCase_C2" tests="1" failures="0" timestamp="16 Apr 2015 04:26:35 GMT" time="0,000" errors="1">
  <testcase name="testCase_C2" time="0,000" classname="com.qtpselenium.suiteC.TestCase_C2">
    <error type="org.testng.TestNGException" message="
Method public void com.qtpselenium.suiteC.TestCase_C2.testCase_C2() requires a @DataProvider named : getTestData">
      <![CDATA[org.testng.TestNGException: 
Method public void com.qtpselenium.suiteC.TestCase_C2.testCase_C2() requires a @DataProvider named : getTestData
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:272)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:385)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1315)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1022)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1122)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1125)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:965)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:961)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:890)
	at org.testng.TestNG.run(TestNG.java:824)
	at org.testng.TestNG.privateMain(TestNG.java:1128)
	at org.testng.TestNG.main(TestNG.java:1092)
]]>
    </error>
  </testcase>
</testsuite>
